### PR TITLE
Finalized Python Package

### PR DESCRIPTION
**Pull request by jbremer**
Hi @jesparza, @Titotix,

This PR includes both PRs from @Titotix and some more love in order to make `peepdf` a true Python package, with its core library accessible through `import peepdf` and the `peepdf.py` command exposed as the global (or local in case of `virtualenv`) `peepdf` command.

In addition to that this PR modifies a few minor things:
- Normalizes the version number to something which gives less problems with Python packages (in this case, version `0.3.1`). This will have to be increased for every release you do.
- Removal of the update functionality, this may be replaced simply by `pip install -U peepdf`.
- Move error logging file from `$GIT/errors.txt` to `~/.peepdf-error.txt`.

I think that's most of it. Now I'd be very happy if you could merge this PR and upload it to PyPI (`python setup.py register` && `python setup.py sdist upload`). I'm also happy to do that for you, but as you're the developer of this library I think it would make most sense if you handle this yourself.

Let me know if there are any questions.

Regards,
Jurriaan

### CODE REVIEW

**Comment by Titotix** [comment]
ahah, we should have communicate. I am currently working in the same way, have a cmd tool and have a full lib capabilities. You can check this out [here](https://github.com/Titotix/peepdf/tree/refactoring)
I don't consider it yet finish so I did not PR yet.
Main changes are :
 - new PDFOutput class which include all method like getPeepJSON, getPeepXML and a new one GetPeepReport (to have a non formated report --> like the one we get when we launch the tool on cli). The code above getPeepReport was duplicated in peepdf.py and PDFConsole.py, not any more here.
 - peepdf/constants.py to have all constants define like authors info but also error path file.

I don't consider it as finish because, for example, all pylibemu features are accessible only through peepdf interactive console, and I would like to access it directly.

**Comment by jbremer** [comment]
One step at a time :-)

**Comment by jbremer** [comment]
@Titotix I did a major refactoring of stuff which will most likely make merging your commits a bit harder.. see also https://github.com/jbremer/peepdf/commit/628ddc98175dc21ab1595591a51c0ca02f00c755

**Comment by ayoubfaouzi** [comment]
Would be nice if we can merge this PR. Thanks a lot !

**Comment by jpic** [comment]
Amazing, thanks for maintaining the library on Pypi ! :tophat:

**Pull request closed without merging**
