### PR TITLE
structure change to install with setup.py

### PR DESCRIPTION
**Pull request by Titotix**
Change structure of the project in order to make setup.py install peepdf properly.

### CODE REVIEW

**Comment by jbremer** [comment]
Great work @Titotix.

**Comment by jbremer** [comment]
Actually, this PR is not complete. As in, it doesn't export a `peepdf` command, and I think it would make more sense to use external dependencies rather than a statically included `jsbeautifier`, `aespython`, and `colorama`.

**Comment by Titotix** [comment]
See #56, it is base don this but also add colorama, aespython and jsbeautifier as external lib

**Comment by jbremer** [comment]
Any status update on this PR? When can we expect a `peepdf` PyPi package?

**Comment by jesparza** [comment]
Hey @jbremer,

I just added a comment in #56. I don't have too much time lately, but one of the issues is that the update functionality is broken with this separation, so I should try to find some time to fix it.

**Pull request closed without merging**
