### PR TITLE
Improve structure to make it easy to install

### PR DESCRIPTION
**Pull request by Titotix**
This PR is based on #52.
It also setup colorama, aespython and jsbeautifier as external lib which are installed by the updated setup.py script.
It updates the README accordingly.

### CODE REVIEW

**Comment by jesparza** [comment]
Hi @Titotix! This looks good, could you also add lxml, PyV8 and pylibemu there?

https://github.com/buffer/pyv8
https://github.com/buffer/pylibemu

**Comment by jesparza** [comment]
I was thinking that the update process maybe could break because of the new structure, something to keep in mind too.

**Comment by Titotix** [comment]
It definitely break the update process. I get somehow lost in my git stuff, so I just come to push the commit which deactivates it and also suggest in the REAMDE to use `easy_install` tool rather than executing manually the `setup.py` script.
easy_install give us the ability to upgrade the soft if we previously have downloaded new version from git, so for now I give the manual process to upgrade.
To note: easy_install won't uninstall the previous version.
The update option should unzip the repo in a temp dir, execute ̀easy_install` on it and then delete the temp dir. This way we could get back a native command to upgrade.
Or we maintain a package on pypi but I guess we both don't want to do that.
But for now I am spliting the code to be able to use it as a lib and as a tool, so the update will wait.

**Comment by jesparza** [comment]
Mmmm, let me think about it, but the update functionality must be present, so I need to take a closer look. I tried that setup.py in my side and I was getting some errors, especially from pythonaes, I changed the dependency link (https://github.com/serprex/pythonaes/tarball/master#egg=package-1.0) and it seems to work now. I will work on making PyV8 and pylibemu work too...

**Comment by Titotix** [comment]
You were write, there were an error but just because setup was not finding the branch 'setup' which was only a local dev branch and I forgot about it when I pushed. But, setup checkout by default on the 'master' branch so the aespython lib was installed anyway. At least on my system, but give me feedback if it still complaign about something now.
So, watch out, I rewrite the history, just `git pull --rebase` and you will be fine.

**Comment by Titotix** [comment]
Ok I added `lxml`as dependency.
I will take care of pyv8 dependency, that's sounds a bit tricky to build both v8 & pyv8. #46.
Could you handle pylibemu @jesparza ?
By the way, what about using [pyExecJS](https://github.com/doloopwhile/PyExecJS) to abstract the JS engine ? And why did you choose v8 at one point ?

**Comment by jesparza** [comment]
Hey!

Pylibemu has been handled by @buffer already, we can just add pylibemu in a requirements.txt file and it will install all the necessary stuff. @buffer was also busy with PyV8 but not sure how far he is or if he needs help for that.

I first used Spidermonkey but installing it was a pain in the ass (more than PyV8) and it did not have support for Windows if I remember correctly. PyV8 looked like a good option and maintained, but now I am not sure anymore. Anyway, I will keep using PyV8 until I release a new version, if not I will not do it any soon ;)

One of the blocking part here is the updating. I need to find some time to figure out a way to avoid breaking the update system, maybe finding the directory where the library is installed and check the files there (sudo will be mandatory, probably).

**Comment by Titotix** [comment]
pyV8 is not anymore really under developement, but I got the idea, we don't have plenty of choice and it's sounds like the best one.
I don't know when did you install pyv8, but it does not work for now. v8 is not checkout neither build in the `setup.py` of @buffer. But perhaps it is in his roadmap. v8 download and compilation has to be done manually for now. But I did not go deep in it yet.

**Comment by buffer** [comment]
Not entirely true. If you clone my own PyV8 repo and you run 'python setup.py install' it will take care of installing both V8 and PyV8 for you. The next step will be uploading it on PyPi but the procedure I described should already work fine. The checkout is not performed because the source code is already in the repo and it is the last version fully supported by PyV8.

**Comment by jbremer** [comment]
@buffer Would you be so awesome to upload it to PyPI?

**Comment by buffer** [comment]
@jbremer FYI a PyV8 package already exists on PyPi but it is really old. A few days ago I contacted the author in order to ask him to update it thus avoiding potential package name confusions. But still no reply from him. In the worst case I will rename and upload it. By the way, the package really needs care. I think we should get together and update it since the last supported version of V8 is quite old. What do you think?

**Comment by jbremer** [comment]
I'm fine with a rename, even if it's just temporarily. What do you mean with *the package really needs care*. Do you mean that your fork of the `PyV8` package is outdated - if so, what would be the alternatives? Are there any?

**Comment by buffer** [comment]
@jbremer I mean that PyV8 code supports currently an old version of PyV8 and it would need to be properly maintained. From time I fix some bugs but probably a different strategy for maintaining it would be worth having. As alternatives, right now the only one available is v8eval but it still lacks some of the key features that are provided by PyV8 instead.

**Comment by Titotix** [comment]
@buffer: ok I need to properly test your repo so.
Basically your are saying that you need people to help you on maintaining it ?
And I guess you mistype Pyv8 & v8 in your last comment :)

**Comment by buffer** [comment]
Yes, I would like having a group of people (and not just me) spending some time and efforts on such repo (PyV8)

**Comment by Titotix** [comment]
Hey
I just come to discover this repo [PyMinRacer](https://github.com/sqreen/PyMiniRacer) mainly from @Lothiraldan. This project come from a company and is under development by 2 dev right now but it's only a 3 months project.
I would be interested to know if @Lothiraldan tested PyV8 and if so to get his opinion.

**Comment by Titotix** [comment]
I close it as this pull is included in #57.

**Pull request closed without merging**
